<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet
    version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    >

  <xsl:template match="Project" mode="output-file">Ampla.Versions.xml</xsl:template>

  <xsl:template match="Project" mode="output" >
	<xsl:param name='filename'/>
    <xsl:param name="this-file">Compare.Ampla.Version.xslt</xsl:param>
    <xsl:comment>Generated by: <xsl:value-of select="$this-file"/></xsl:comment>
    <xsl:element name='Properties'>
		<xsl:apply-templates select='/Project/Properties/*' mode='copy'>
			<xsl:sort select='@name'/>
		</xsl:apply-templates>
    </xsl:element>
  </xsl:template>
  
</xsl:stylesheet>
