<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet
    version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    >

  <xsl:template match="Reference/Type" mode="output-file">
	<xsl:value-of select="concat('Type\', ../@name, '\', @name, '.xml')"/>
  </xsl:template>

  <xsl:template match="Reference/Type" mode="output-mode">text</xsl:template>
	
  <xsl:template match="Reference/Type" mode="output" >
	<xsl:param name='filename'/>
    <xsl:param name="this-file">Include.Reference.Type.xslt</xsl:param>
    <xsl:comment>Generated by: <xsl:value-of select="$this-file"/></xsl:comment>
	<xsl:variable name='type' select='@fullName'/>
	<xsl:variable name='items' select='//Item[@type=$type]'/>
	
	<xsl:value-of select="concat('Type : ', $type, $crlf)"/>
	<xsl:value-of select="concat('Count: ', count($items), ' items', $crlf)"/>
	<xsl:for-each select='//Item[@type=$type]'>
		<xsl:sort select='@fullName'/>
		<xsl:value-of select="concat(@fullName, $crlf)"/>
	</xsl:for-each>
  </xsl:template>
  
</xsl:stylesheet>
