<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet
    version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    >

  <xsl:template match="Item[@type='Citect.Ampla.StandardItems.Code']" mode="output-file">
	<xsl:value-of select="concat('Code\', @fullName, '.cs')"/>
  </xsl:template>

  <xsl:template match="Item[@type='Citect.Ampla.StandardItems.Code']" mode="output-mode">text</xsl:template>

  <xsl:template match="Item[@type='Citect.Ampla.StandardItems.Code']" mode="output" >
	<xsl:param name='filename'/>
    <xsl:param name="this-file">Include.Code.xslt</xsl:param>
	<xsl:text>// Generated by: </xsl:text><xsl:value-of select="$this-file"/>
	<xsl:value-of select="Property[@name='Source']"/>
  </xsl:template>
  
</xsl:stylesheet>
